#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "${repo_root}/scripts/version"
mkdir -p "${repo_root}/bin"
cd "${repo_root}"
CGO_ENABLED=0 go build -mod=mod -trimpath -buildvcs=false \
    -ldflags "-s -w -buildid= -X main.VERSION=${VERSION}" \
    -o bin/kubernetes-authentication-bridge .
